---
- name: Install docker packages 
  apt: 
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: present
    update_cache: yes
  tags:
    - docker
  
- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: 
    - docker
      
- name: Verify key with fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
  
- name: Set up the stable repository
  # For Ubuntu 18.04 :
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes
  tags:
    - docker

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags: 
    - docker

# sudo apt-get install docker engine
- name: Install docker
  apt:
    name: docker-ce=5:18.09.6~3-0~ubuntu-bionic
    state: present
    update_cache: yes
  notify: docker_restart
  tags: 
    - docker

- name: Start docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes

# sudo usermod -aG docker ubuntu
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  tags:
    - docker

